# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: STYLAN
email: duan-deqing@foxmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a blog about my learning and work experience in the field of software development. 
baseurl: "/github-pages-with-docker" # the subpath of your site, e.g. /blog
url: "https://duan-deqing.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# minima 已经默认定义的变量
author: duan-deqing
github_username:  duan-deqing

# 自定义新的社交链接
# 具体的设置代码在 _includes/social.html 文件中
# 格式如下：注意id和username缺一不可，id对应B站UID，username可以随意设置
# bilibili_id: "18756460"
# bilibili_username: stylan
bilibili_id: "18756460"
bilibili_username: stylan

# 添加一个版权信息，变量标志加年份
# Copyright: Company Name, Inc.
copyright: "STYLAN "

# title-logo 自定义变量，指向图片地址，使用时会在标题栏显示图片
# 而不显示文字标题，图片建议尺寸高度为 50px，支持 png、jpg、svg 等格式
# 图片地址使用相对路径，相对于站点根目录，例如：/assets/images/logo.png
# title-logo: /assets/images/logo.png
title-logo: 

# Build settings
# 这两个不需要改，改了会导致无法正常显示
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
